# Tensors
A nuber, vector, matrix or any N dimensional array
Everything is made up of tensors

In [10]:
import torch # Importing pytorch

Creating tensors

In [9]:
# Number tensor
t1 = torch.tensor(4.) # 4. is short for 4.0
print(t1)
print(t1.dtype)

tensor(4.)
torch.float32


In [8]:
# Vector tensor
t2 = torch.tensor([1.,2,3,4,5])
print(t2) # everythons gets converted to the same datatype
print(t2.dtype)

tensor([1., 2., 3., 4., 5.])
torch.float32


In [12]:
# Matrix Tensor
t3 = torch.tensor([[1.,2],[4,5],[3,6]])
print(t3)
print(t3.dtype)

tensor([[1., 2.],
        [4., 5.],
        [3., 6.]])
torch.float32


In [14]:
# 3D tensor
t4 = torch.tensor([[[1,2,3],[4,5,6]],[[9,6,3],[1,6,4]]])
t4

tensor([[[1, 2, 3],
         [4, 5, 6]],

        [[9, 6, 3],
         [1, 6, 4]]])

Unlike list of lists, tensors should have a regular shape\
same number of elements in each list\
Dimension of a tensor is determined by the number of elements moving from the outermost list to the inner

In [17]:
print(t1,t1.shape) #empty list coz tensor is just a number
print(t2,t2.shape)
print(t3,t3.shape)
print(t4,t4.shape)

tensor(4.) torch.Size([])
tensor([1., 2., 3., 4., 5.]) torch.Size([5])
tensor([[1., 2.],
        [4., 5.],
        [3., 6.]]) torch.Size([3, 2])
tensor([[[1, 2, 3],
         [4, 5, 6]],

        [[9, 6, 3],
         [1, 6, 4]]]) torch.Size([2, 2, 3])
