<a href="https://colab.research.google.com/github/ankushKun/learning-ML/blob/master/day2/Tensor_operations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Operations on tensors

In [ ]:
import torch

In [ ]:
x = torch.tensor(3.)
w = torch.tensor(4.,requires_grad=True)
z = torch.tensor(5.,requires_grad=True)

performing normal math operations on tensors

In [ ]:
y = x*w+z
print(y)

tensor(17., grad_fn=<AddBackward0>)


we can also find derivatives of tensors which have requires_grad=True\
derivatives is important for gradient descent algorithm\
**tensor.backward()** is used to compute derivatives\
PS - *dont run it more than once or it will throw errors*

In [ ]:
y.backward()

derivatives of y with respect to input tensors(x,w,z) are stored in their **.grad** property\
gradient and derivatives are the samething\
gradient used when dealing with matrices\
derivative used when dealing with numbers

In [ ]:
# derivative of 
print("dy/dx:",x.grad) # None because x doesnot have requires_grad=True
print("dy/dw:",w.grad)
print("dy/dz:",z.grad)

dy/dx: None
dy/dw: tensor(3.)
dy/dz: tensor(1.)


In [ ]:
a = torch.tensor([[1.,2],[2,1]],requires_grad=True)
b = torch.tensor([[4.,5],[3,2]],requires_grad=True)
c = a+b
#c.backward()
print(a.grad)

None


**.backward()** only works on scalar/0D values +_+

In [ ]:
y = x+w+z
z = y*x
#z.backward()
w.grad, x.grad, z.grad

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:4: UserWarning: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad attribute won't be populated during autograd.backward(). If you indeed want the gradient for a non-leaf Tensor, use .retain_grad() on the non-leaf Tensor. If you access the non-leaf Tensor by mistake, make sure you access the leaf Tensor instead. See github.com/pytorch/pytorch/pull/30531 for more informations.
  after removing the cwd from sys.path.


(tensor(3.), None, None)

# Pytorch with numpy

In [ ]:
import numpy as np

In [ ]:
x = np.array([[1.,2],[3,4]])
print(x)

[[1. 2.]
 [3. 4.]]


numpy array to pytorch tensor

In [ ]:
y1 = torch.from_numpy(x) # uses the same memory space
y2 = torch.tensor(x)     # creates a copy allots new memory space
print(y1)
print(y2)

tensor([[1., 2.],
        [3., 4.]], dtype=torch.float64)
tensor([[1., 2.],
        [3., 4.]], dtype=torch.float64)


In [ ]:
print(x.dtype) #np array
print(y1.dtype)#tensor
print(y2.dtype)#tensor

float64
torch.float64
torch.float64


pytorch tensor to numpy array

In [ ]:
z = y1.numpy()
z

array([[1., 2.],
       [3., 4.]])